services:
  - type: web
    name: leetcode-ladder
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.8.10
