services:
  - type: web
    name: leetcode-ladder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
      - key: FLASK_ENV
        value: production
    autoDeploy: true
