name: Weekly Problem Update

# Add permissions here
permissions:
  contents: write

on:
  schedule:
    # Runs at 00:00 UTC on Wednesday
    - cron: '0 0 * * 3'
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager  # Ensure selenium is installed
          
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Run pipeline script
        run: |
          echo "Running pipeline script..."
          python run_pipeline.py
          echo "Pipeline script finished"
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          
          # Only commit if there are changes
          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "Weekly automatic update of problem ratings ($(date +%Y-%m-%d))"
            git push origin main # Explicitly push to main branch
          fi